CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(128) UNIQUE,
  "email" varchar(128) UNIQUE NOT NULL,
  "img" varchar(255),
  "pwd" varchar(128) NOT NULL
);

CREATE TABLE "auth_token" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "refresh_token" varchar(255) UNIQUE NOT NULL,
  "expires_at" timestamp NOT NULL
);

CREATE TABLE "advertisement" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ads_name" varchar(255) NOT NULL,
  "location" varchar(255) NOT NULL,
  "size_length" decimal,
  "size_height" decimal,
  "latitude" decimal(10,8),
  "longitude" decimal(11,8),
  "user_id" int NOT NULL,
  "ads_type_id" int,
  "ads_status_id" int,
  "city_id" int
);

CREATE TABLE "ads_status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "status_detail" varchar(255) NOT NULL
);

CREATE TABLE "ads_type" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "ads_type" varchar(255) NOT NULL
);

CREATE TABLE "city" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "city_name" varchar(255) NOT NULL,
  "country_id" int NOT NULL
);

CREATE TABLE "country" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "country_name" varchar(255) UNIQUE NOT NULL
);

CREATE TABLE "image" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ads_id" int NOT NULL,
  "url" varchar(255)
);

CREATE TABLE "contact_agent" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "contact_name" varchar(255),
  "mobile_number" varchar(20),
  "contact_email" varchar(128)
);

ALTER TABLE "auth_token" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "advertisement" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "advertisement" ADD FOREIGN KEY ("ads_type_id") REFERENCES "ads_type" ("id");

ALTER TABLE "advertisement" ADD FOREIGN KEY ("ads_status_id") REFERENCES "ads_status" ("id");

ALTER TABLE "advertisement" ADD FOREIGN KEY ("city_id") REFERENCES "city" ("id");

ALTER TABLE "city" ADD FOREIGN KEY ("country_id") REFERENCES "country" ("id");

ALTER TABLE "contact_agent" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "image" ADD FOREIGN KEY ("ads_id") REFERENCES "advertisement" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
